# -*- coding: utf-8 -*-
"""Task_3-Password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13X1eUZadImvSXYdpHkKtFzzrmYmMANG-
"""

import random
import string

def generate_password(length):
    if length < 5:
        print("Password length should be at least 4 for better security.")
        return None

    # Character categories
    lower = string.ascii_lowercase
    upper = string.ascii_uppercase
    digits = string.digits
    special = string.punctuation

    # Ensuring at least one character from each category
    all_characters = lower + upper + digits + special
    password = [
        random.choice(lower),
        random.choice(upper),
        random.choice(digits),
        random.choice(special)
    ]

    # Filling the rest of the password length with random choices
    password += random.choices(all_characters, k=length -5)

    # Shuffling to avoid predictable patterns
    random.shuffle(password)

    return ''.join(password)

# Input from user
try:
    length = int(input("Enter the desired password length: "))
    generated_password = generate_password(length)
    if generated_password:
        print(f"Generated Password: {generated_password}")
except ValueError:
    print("Please enter a valid number.")