# -*- coding: utf-8 -*-
"""task -3 calcualator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pQQQdp53znSaj9kxD6KisqiF-eL5RO3
"""

def calculator():
    print("Welcome to the Calculator!")
    print("Select operation:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")

    def add(a, b):
        return a + b

    def subtract(a, b):
        return a - b

    def multiply(a, b):
        return a * b

    def divide(a, b):
        if b == 0:
            return "Error: Division by zero is not allowed!"
        return a / b

    # Dictionary to simulate switch cases
    operations = {
        '1': add,
        '2': subtract,
        '3': multiply,
        '4': divide
    }

    while True:
        choice = input("Enter choice (1/2/3/4): ")

        if choice not in operations:
            print("Invalid choice. Please choose a valid operation.")
            continue

        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            result = operations[choice](num1, num2)
            print(f"The result is: {result}")
        except ValueError:
            print("Invalid input! Please enter numeric values.")

        next_calculation = input("Do you want to perform another calculation? (yes/no): ").lower()
        if next_calculation != 'yes':
            print("Thank you for using the calculator. Goodbye!")
            break

# Run the calculator
calculator()